// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Game.Qe.Common.Msg.Proto {

  /// <summary>Holder for reflection information generated from GameMsg.proto</summary>
  public static partial class GameMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for GameMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1HYW1lTXNnLnByb3RvEhhnYW1lLnFlLmNvbW1vbi5tc2cucHJvdG8iogEK",
            "FVNTX2dhbWVfbWFwX2V2ZW50X21zZxIPCgdldmVudElkGAEgASgFEhEKCWZy",
            "b21NYXBJZBgCIAEoBRISCgpmcm9tUm9vbUlkGAMgASgFEg8KB3RvTWFwSWQY",
            "BCABKAUSEAoIdG9Sb29tSWQYBSABKAUSCwoDY21kGAYgASgJEg4KBnBhcmFt",
            "cxgHIAMoBRIRCglzdHJQYXJhbXMYCCADKAkilgEKFlNTX2dhbWVfcm9sZV9l",
            "dmVudF9tc2cSDwoHZXZlbnRJZBgBIAEoBRIQCghwbGF5ZXJJZBgCIAEoAxIO",
            "CgZyb2xlSWQYAyABKAMSDQoFbWFwSWQYBCABKAUSDgoGcm9vbUlkGAUgASgF",
            "Eg0KBW9iaklkGAYgASgDEgsKA2NtZBgHIAEoCRIOCgZwYXJhbXMYCCADKAUi",
            "3wEKFVNTX2dhbWVfcm9sZV9qdW1wX21zZxIMCgRzdGVwGAEgASgFEhAKCHBs",
            "YXllcklkGAIgASgDEg4KBnJvbGVJZBgDIAEoAxIRCglmcm9tTWFwSWQYBCAB",
            "KAUSEgoKZnJvbVJvb21JZBgFIAEoBRIPCgd0b01hcElkGAYgASgFEhAKCHRv",
            "Um9vbUlkGAcgASgFEg0KBXBvaW50GAggASgFEgwKBGRpc3QYCSABKAUSDQoF",
            "Zm9yY2UYCiABKAgSDgoGcGFyYW1zGAsgAygFEhAKCHRvUm9sZUlkGAwgASgD",
            "IpwBChdTU19nYW1lX29iamVjdF9qdW1wX21zZxIMCgR0eXBlGAEgASgFEgoK",
            "AmlkGAIgASgDEhEKCWZyb21NYXBJZBgDIAEoBRISCgpmcm9tUm9vbUlkGAQg",
            "ASgFEg8KB3RvTWFwSWQYBSABKAUSEAoIdG9Sb29tSWQYBiABKAUSDQoFcG9p",
            "bnQYByABKAUSDgoGcGFyYW1zGAggAygFQg9aDXFlL3Byb3RvL2dhbWViBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Qe.Common.Msg.Proto.SS_game_map_event_msg), global::Game.Qe.Common.Msg.Proto.SS_game_map_event_msg.Parser, new[]{ "EventId", "FromMapId", "FromRoomId", "ToMapId", "ToRoomId", "Cmd", "Params", "StrParams" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Qe.Common.Msg.Proto.SS_game_role_event_msg), global::Game.Qe.Common.Msg.Proto.SS_game_role_event_msg.Parser, new[]{ "EventId", "PlayerId", "RoleId", "MapId", "RoomId", "ObjId", "Cmd", "Params" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Qe.Common.Msg.Proto.SS_game_role_jump_msg), global::Game.Qe.Common.Msg.Proto.SS_game_role_jump_msg.Parser, new[]{ "Step", "PlayerId", "RoleId", "FromMapId", "FromRoomId", "ToMapId", "ToRoomId", "Point", "Dist", "Force", "Params", "ToRoleId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Game.Qe.Common.Msg.Proto.SS_game_object_jump_msg), global::Game.Qe.Common.Msg.Proto.SS_game_object_jump_msg.Parser, new[]{ "Type", "Id", "FromMapId", "FromRoomId", "ToMapId", "ToRoomId", "Point", "Params" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///服务器之间传递地图事件
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SS_game_map_event_msg : pb::IMessage<SS_game_map_event_msg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS_game_map_event_msg> _parser = new pb::MessageParser<SS_game_map_event_msg>(() => new SS_game_map_event_msg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS_game_map_event_msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Qe.Common.Msg.Proto.GameMsgReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS_game_map_event_msg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS_game_map_event_msg(SS_game_map_event_msg other) : this() {
      eventId_ = other.eventId_;
      fromMapId_ = other.fromMapId_;
      fromRoomId_ = other.fromRoomId_;
      toMapId_ = other.toMapId_;
      toRoomId_ = other.toRoomId_;
      cmd_ = other.cmd_;
      params_ = other.params_.Clone();
      strParams_ = other.strParams_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS_game_map_event_msg Clone() {
      return new SS_game_map_event_msg(this);
    }

    /// <summary>Field number for the "eventId" field.</summary>
    public const int EventIdFieldNumber = 1;
    private int eventId_;
    /// <summary>
    ///事件ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EventId {
      get { return eventId_; }
      set {
        eventId_ = value;
      }
    }

    /// <summary>Field number for the "fromMapId" field.</summary>
    public const int FromMapIdFieldNumber = 2;
    private int fromMapId_;
    /// <summary>
    ///来源地图
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FromMapId {
      get { return fromMapId_; }
      set {
        fromMapId_ = value;
      }
    }

    /// <summary>Field number for the "fromRoomId" field.</summary>
    public const int FromRoomIdFieldNumber = 3;
    private int fromRoomId_;
    /// <summary>
    ///来源房间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FromRoomId {
      get { return fromRoomId_; }
      set {
        fromRoomId_ = value;
      }
    }

    /// <summary>Field number for the "toMapId" field.</summary>
    public const int ToMapIdFieldNumber = 4;
    private int toMapId_;
    /// <summary>
    ///目标地图ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ToMapId {
      get { return toMapId_; }
      set {
        toMapId_ = value;
      }
    }

    /// <summary>Field number for the "toRoomId" field.</summary>
    public const int ToRoomIdFieldNumber = 5;
    private int toRoomId_;
    /// <summary>
    ///目标房间ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ToRoomId {
      get { return toRoomId_; }
      set {
        toRoomId_ = value;
      }
    }

    /// <summary>Field number for the "cmd" field.</summary>
    public const int CmdFieldNumber = 6;
    private string cmd_ = "";
    /// <summary>
    ///命令
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cmd {
      get { return cmd_; }
      set {
        cmd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "params" field.</summary>
    public const int ParamsFieldNumber = 7;
    private static readonly pb::FieldCodec<int> _repeated_params_codec
        = pb::FieldCodec.ForInt32(58);
    private readonly pbc::RepeatedField<int> params_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///参数数组
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Params {
      get { return params_; }
    }

    /// <summary>Field number for the "strParams" field.</summary>
    public const int StrParamsFieldNumber = 8;
    private static readonly pb::FieldCodec<string> _repeated_strParams_codec
        = pb::FieldCodec.ForString(66);
    private readonly pbc::RepeatedField<string> strParams_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> StrParams {
      get { return strParams_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS_game_map_event_msg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS_game_map_event_msg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventId != other.EventId) return false;
      if (FromMapId != other.FromMapId) return false;
      if (FromRoomId != other.FromRoomId) return false;
      if (ToMapId != other.ToMapId) return false;
      if (ToRoomId != other.ToRoomId) return false;
      if (Cmd != other.Cmd) return false;
      if(!params_.Equals(other.params_)) return false;
      if(!strParams_.Equals(other.strParams_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventId != 0) hash ^= EventId.GetHashCode();
      if (FromMapId != 0) hash ^= FromMapId.GetHashCode();
      if (FromRoomId != 0) hash ^= FromRoomId.GetHashCode();
      if (ToMapId != 0) hash ^= ToMapId.GetHashCode();
      if (ToRoomId != 0) hash ^= ToRoomId.GetHashCode();
      if (Cmd.Length != 0) hash ^= Cmd.GetHashCode();
      hash ^= params_.GetHashCode();
      hash ^= strParams_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EventId);
      }
      if (FromMapId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FromMapId);
      }
      if (FromRoomId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FromRoomId);
      }
      if (ToMapId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ToMapId);
      }
      if (ToRoomId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ToRoomId);
      }
      if (Cmd.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Cmd);
      }
      params_.WriteTo(output, _repeated_params_codec);
      strParams_.WriteTo(output, _repeated_strParams_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EventId);
      }
      if (FromMapId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(FromMapId);
      }
      if (FromRoomId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FromRoomId);
      }
      if (ToMapId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ToMapId);
      }
      if (ToRoomId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ToRoomId);
      }
      if (Cmd.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Cmd);
      }
      params_.WriteTo(ref output, _repeated_params_codec);
      strParams_.WriteTo(ref output, _repeated_strParams_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EventId);
      }
      if (FromMapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FromMapId);
      }
      if (FromRoomId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FromRoomId);
      }
      if (ToMapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ToMapId);
      }
      if (ToRoomId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ToRoomId);
      }
      if (Cmd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cmd);
      }
      size += params_.CalculateSize(_repeated_params_codec);
      size += strParams_.CalculateSize(_repeated_strParams_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS_game_map_event_msg other) {
      if (other == null) {
        return;
      }
      if (other.EventId != 0) {
        EventId = other.EventId;
      }
      if (other.FromMapId != 0) {
        FromMapId = other.FromMapId;
      }
      if (other.FromRoomId != 0) {
        FromRoomId = other.FromRoomId;
      }
      if (other.ToMapId != 0) {
        ToMapId = other.ToMapId;
      }
      if (other.ToRoomId != 0) {
        ToRoomId = other.ToRoomId;
      }
      if (other.Cmd.Length != 0) {
        Cmd = other.Cmd;
      }
      params_.Add(other.params_);
      strParams_.Add(other.strParams_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventId = input.ReadInt32();
            break;
          }
          case 16: {
            FromMapId = input.ReadInt32();
            break;
          }
          case 24: {
            FromRoomId = input.ReadInt32();
            break;
          }
          case 32: {
            ToMapId = input.ReadInt32();
            break;
          }
          case 40: {
            ToRoomId = input.ReadInt32();
            break;
          }
          case 50: {
            Cmd = input.ReadString();
            break;
          }
          case 58:
          case 56: {
            params_.AddEntriesFrom(input, _repeated_params_codec);
            break;
          }
          case 66: {
            strParams_.AddEntriesFrom(input, _repeated_strParams_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EventId = input.ReadInt32();
            break;
          }
          case 16: {
            FromMapId = input.ReadInt32();
            break;
          }
          case 24: {
            FromRoomId = input.ReadInt32();
            break;
          }
          case 32: {
            ToMapId = input.ReadInt32();
            break;
          }
          case 40: {
            ToRoomId = input.ReadInt32();
            break;
          }
          case 50: {
            Cmd = input.ReadString();
            break;
          }
          case 58:
          case 56: {
            params_.AddEntriesFrom(ref input, _repeated_params_codec);
            break;
          }
          case 66: {
            strParams_.AddEntriesFrom(ref input, _repeated_strParams_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///服务器之间传递角色事件
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SS_game_role_event_msg : pb::IMessage<SS_game_role_event_msg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS_game_role_event_msg> _parser = new pb::MessageParser<SS_game_role_event_msg>(() => new SS_game_role_event_msg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS_game_role_event_msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Qe.Common.Msg.Proto.GameMsgReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS_game_role_event_msg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS_game_role_event_msg(SS_game_role_event_msg other) : this() {
      eventId_ = other.eventId_;
      playerId_ = other.playerId_;
      roleId_ = other.roleId_;
      mapId_ = other.mapId_;
      roomId_ = other.roomId_;
      objId_ = other.objId_;
      cmd_ = other.cmd_;
      params_ = other.params_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS_game_role_event_msg Clone() {
      return new SS_game_role_event_msg(this);
    }

    /// <summary>Field number for the "eventId" field.</summary>
    public const int EventIdFieldNumber = 1;
    private int eventId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EventId {
      get { return eventId_; }
      set {
        eventId_ = value;
      }
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 2;
    private long playerId_;
    /// <summary>
    ///账号ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "roleId" field.</summary>
    public const int RoleIdFieldNumber = 3;
    private long roleId_;
    /// <summary>
    ///角色ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RoleId {
      get { return roleId_; }
      set {
        roleId_ = value;
      }
    }

    /// <summary>Field number for the "mapId" field.</summary>
    public const int MapIdFieldNumber = 4;
    private int mapId_;
    /// <summary>
    ///地图ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MapId {
      get { return mapId_; }
      set {
        mapId_ = value;
      }
    }

    /// <summary>Field number for the "roomId" field.</summary>
    public const int RoomIdFieldNumber = 5;
    private int roomId_;
    /// <summary>
    ///房间ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RoomId {
      get { return roomId_; }
      set {
        roomId_ = value;
      }
    }

    /// <summary>Field number for the "objId" field.</summary>
    public const int ObjIdFieldNumber = 6;
    private long objId_;
    /// <summary>
    ///地图对象ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ObjId {
      get { return objId_; }
      set {
        objId_ = value;
      }
    }

    /// <summary>Field number for the "cmd" field.</summary>
    public const int CmdFieldNumber = 7;
    private string cmd_ = "";
    /// <summary>
    ///命令
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Cmd {
      get { return cmd_; }
      set {
        cmd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "params" field.</summary>
    public const int ParamsFieldNumber = 8;
    private static readonly pb::FieldCodec<int> _repeated_params_codec
        = pb::FieldCodec.ForInt32(66);
    private readonly pbc::RepeatedField<int> params_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///参数数组
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Params {
      get { return params_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS_game_role_event_msg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS_game_role_event_msg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventId != other.EventId) return false;
      if (PlayerId != other.PlayerId) return false;
      if (RoleId != other.RoleId) return false;
      if (MapId != other.MapId) return false;
      if (RoomId != other.RoomId) return false;
      if (ObjId != other.ObjId) return false;
      if (Cmd != other.Cmd) return false;
      if(!params_.Equals(other.params_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EventId != 0) hash ^= EventId.GetHashCode();
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      if (RoleId != 0L) hash ^= RoleId.GetHashCode();
      if (MapId != 0) hash ^= MapId.GetHashCode();
      if (RoomId != 0) hash ^= RoomId.GetHashCode();
      if (ObjId != 0L) hash ^= ObjId.GetHashCode();
      if (Cmd.Length != 0) hash ^= Cmd.GetHashCode();
      hash ^= params_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EventId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EventId);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerId);
      }
      if (RoleId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(RoleId);
      }
      if (MapId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(MapId);
      }
      if (RoomId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(RoomId);
      }
      if (ObjId != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(ObjId);
      }
      if (Cmd.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Cmd);
      }
      params_.WriteTo(output, _repeated_params_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EventId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EventId);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerId);
      }
      if (RoleId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(RoleId);
      }
      if (MapId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(MapId);
      }
      if (RoomId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(RoomId);
      }
      if (ObjId != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(ObjId);
      }
      if (Cmd.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Cmd);
      }
      params_.WriteTo(ref output, _repeated_params_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EventId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EventId);
      }
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (RoleId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RoleId);
      }
      if (MapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MapId);
      }
      if (RoomId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RoomId);
      }
      if (ObjId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ObjId);
      }
      if (Cmd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cmd);
      }
      size += params_.CalculateSize(_repeated_params_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS_game_role_event_msg other) {
      if (other == null) {
        return;
      }
      if (other.EventId != 0) {
        EventId = other.EventId;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      if (other.RoleId != 0L) {
        RoleId = other.RoleId;
      }
      if (other.MapId != 0) {
        MapId = other.MapId;
      }
      if (other.RoomId != 0) {
        RoomId = other.RoomId;
      }
      if (other.ObjId != 0L) {
        ObjId = other.ObjId;
      }
      if (other.Cmd.Length != 0) {
        Cmd = other.Cmd;
      }
      params_.Add(other.params_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventId = input.ReadInt32();
            break;
          }
          case 16: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            RoleId = input.ReadInt64();
            break;
          }
          case 32: {
            MapId = input.ReadInt32();
            break;
          }
          case 40: {
            RoomId = input.ReadInt32();
            break;
          }
          case 48: {
            ObjId = input.ReadInt64();
            break;
          }
          case 58: {
            Cmd = input.ReadString();
            break;
          }
          case 66:
          case 64: {
            params_.AddEntriesFrom(input, _repeated_params_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EventId = input.ReadInt32();
            break;
          }
          case 16: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            RoleId = input.ReadInt64();
            break;
          }
          case 32: {
            MapId = input.ReadInt32();
            break;
          }
          case 40: {
            RoomId = input.ReadInt32();
            break;
          }
          case 48: {
            ObjId = input.ReadInt64();
            break;
          }
          case 58: {
            Cmd = input.ReadString();
            break;
          }
          case 66:
          case 64: {
            params_.AddEntriesFrom(ref input, _repeated_params_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SS_game_role_jump_msg : pb::IMessage<SS_game_role_jump_msg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS_game_role_jump_msg> _parser = new pb::MessageParser<SS_game_role_jump_msg>(() => new SS_game_role_jump_msg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS_game_role_jump_msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Qe.Common.Msg.Proto.GameMsgReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS_game_role_jump_msg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS_game_role_jump_msg(SS_game_role_jump_msg other) : this() {
      step_ = other.step_;
      playerId_ = other.playerId_;
      roleId_ = other.roleId_;
      fromMapId_ = other.fromMapId_;
      fromRoomId_ = other.fromRoomId_;
      toMapId_ = other.toMapId_;
      toRoomId_ = other.toRoomId_;
      point_ = other.point_;
      dist_ = other.dist_;
      force_ = other.force_;
      params_ = other.params_.Clone();
      toRoleId_ = other.toRoleId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS_game_role_jump_msg Clone() {
      return new SS_game_role_jump_msg(this);
    }

    /// <summary>Field number for the "step" field.</summary>
    public const int StepFieldNumber = 1;
    private int step_;
    /// <summary>
    ///步骤 0：请求跳转 1:离开地图 2:进入地图
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Step {
      get { return step_; }
      set {
        step_ = value;
      }
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 2;
    private long playerId_;
    /// <summary>
    ///账号ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "roleId" field.</summary>
    public const int RoleIdFieldNumber = 3;
    private long roleId_;
    /// <summary>
    ///角色ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RoleId {
      get { return roleId_; }
      set {
        roleId_ = value;
      }
    }

    /// <summary>Field number for the "fromMapId" field.</summary>
    public const int FromMapIdFieldNumber = 4;
    private int fromMapId_;
    /// <summary>
    ///来源地图ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FromMapId {
      get { return fromMapId_; }
      set {
        fromMapId_ = value;
      }
    }

    /// <summary>Field number for the "fromRoomId" field.</summary>
    public const int FromRoomIdFieldNumber = 5;
    private int fromRoomId_;
    /// <summary>
    ///来源房间ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FromRoomId {
      get { return fromRoomId_; }
      set {
        fromRoomId_ = value;
      }
    }

    /// <summary>Field number for the "toMapId" field.</summary>
    public const int ToMapIdFieldNumber = 6;
    private int toMapId_;
    /// <summary>
    ///目标地图ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ToMapId {
      get { return toMapId_; }
      set {
        toMapId_ = value;
      }
    }

    /// <summary>Field number for the "toRoomId" field.</summary>
    public const int ToRoomIdFieldNumber = 7;
    private int toRoomId_;
    /// <summary>
    ///目标房间ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ToRoomId {
      get { return toRoomId_; }
      set {
        toRoomId_ = value;
      }
    }

    /// <summary>Field number for the "point" field.</summary>
    public const int PointFieldNumber = 8;
    private int point_;
    /// <summary>
    ///坐标
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Point {
      get { return point_; }
      set {
        point_ = value;
      }
    }

    /// <summary>Field number for the "dist" field.</summary>
    public const int DistFieldNumber = 9;
    private int dist_;
    /// <summary>
    ///坐标范围
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Dist {
      get { return dist_; }
      set {
        dist_ = value;
      }
    }

    /// <summary>Field number for the "force" field.</summary>
    public const int ForceFieldNumber = 10;
    private bool force_;
    /// <summary>
    ///强制(忽略地图是否开启)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Force {
      get { return force_; }
      set {
        force_ = value;
      }
    }

    /// <summary>Field number for the "params" field.</summary>
    public const int ParamsFieldNumber = 11;
    private static readonly pb::FieldCodec<int> _repeated_params_codec
        = pb::FieldCodec.ForInt32(90);
    private readonly pbc::RepeatedField<int> params_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Params {
      get { return params_; }
    }

    /// <summary>Field number for the "toRoleId" field.</summary>
    public const int ToRoleIdFieldNumber = 12;
    private long toRoleId_;
    /// <summary>
    /// 目标角色
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ToRoleId {
      get { return toRoleId_; }
      set {
        toRoleId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS_game_role_jump_msg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS_game_role_jump_msg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Step != other.Step) return false;
      if (PlayerId != other.PlayerId) return false;
      if (RoleId != other.RoleId) return false;
      if (FromMapId != other.FromMapId) return false;
      if (FromRoomId != other.FromRoomId) return false;
      if (ToMapId != other.ToMapId) return false;
      if (ToRoomId != other.ToRoomId) return false;
      if (Point != other.Point) return false;
      if (Dist != other.Dist) return false;
      if (Force != other.Force) return false;
      if(!params_.Equals(other.params_)) return false;
      if (ToRoleId != other.ToRoleId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Step != 0) hash ^= Step.GetHashCode();
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      if (RoleId != 0L) hash ^= RoleId.GetHashCode();
      if (FromMapId != 0) hash ^= FromMapId.GetHashCode();
      if (FromRoomId != 0) hash ^= FromRoomId.GetHashCode();
      if (ToMapId != 0) hash ^= ToMapId.GetHashCode();
      if (ToRoomId != 0) hash ^= ToRoomId.GetHashCode();
      if (Point != 0) hash ^= Point.GetHashCode();
      if (Dist != 0) hash ^= Dist.GetHashCode();
      if (Force != false) hash ^= Force.GetHashCode();
      hash ^= params_.GetHashCode();
      if (ToRoleId != 0L) hash ^= ToRoleId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Step != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Step);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerId);
      }
      if (RoleId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(RoleId);
      }
      if (FromMapId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(FromMapId);
      }
      if (FromRoomId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(FromRoomId);
      }
      if (ToMapId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ToMapId);
      }
      if (ToRoomId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ToRoomId);
      }
      if (Point != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Point);
      }
      if (Dist != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Dist);
      }
      if (Force != false) {
        output.WriteRawTag(80);
        output.WriteBool(Force);
      }
      params_.WriteTo(output, _repeated_params_codec);
      if (ToRoleId != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(ToRoleId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Step != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Step);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerId);
      }
      if (RoleId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(RoleId);
      }
      if (FromMapId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(FromMapId);
      }
      if (FromRoomId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(FromRoomId);
      }
      if (ToMapId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ToMapId);
      }
      if (ToRoomId != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ToRoomId);
      }
      if (Point != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Point);
      }
      if (Dist != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Dist);
      }
      if (Force != false) {
        output.WriteRawTag(80);
        output.WriteBool(Force);
      }
      params_.WriteTo(ref output, _repeated_params_codec);
      if (ToRoleId != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(ToRoleId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Step != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Step);
      }
      if (PlayerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (RoleId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RoleId);
      }
      if (FromMapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FromMapId);
      }
      if (FromRoomId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FromRoomId);
      }
      if (ToMapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ToMapId);
      }
      if (ToRoomId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ToRoomId);
      }
      if (Point != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Point);
      }
      if (Dist != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Dist);
      }
      if (Force != false) {
        size += 1 + 1;
      }
      size += params_.CalculateSize(_repeated_params_codec);
      if (ToRoleId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ToRoleId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS_game_role_jump_msg other) {
      if (other == null) {
        return;
      }
      if (other.Step != 0) {
        Step = other.Step;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      if (other.RoleId != 0L) {
        RoleId = other.RoleId;
      }
      if (other.FromMapId != 0) {
        FromMapId = other.FromMapId;
      }
      if (other.FromRoomId != 0) {
        FromRoomId = other.FromRoomId;
      }
      if (other.ToMapId != 0) {
        ToMapId = other.ToMapId;
      }
      if (other.ToRoomId != 0) {
        ToRoomId = other.ToRoomId;
      }
      if (other.Point != 0) {
        Point = other.Point;
      }
      if (other.Dist != 0) {
        Dist = other.Dist;
      }
      if (other.Force != false) {
        Force = other.Force;
      }
      params_.Add(other.params_);
      if (other.ToRoleId != 0L) {
        ToRoleId = other.ToRoleId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Step = input.ReadInt32();
            break;
          }
          case 16: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            RoleId = input.ReadInt64();
            break;
          }
          case 32: {
            FromMapId = input.ReadInt32();
            break;
          }
          case 40: {
            FromRoomId = input.ReadInt32();
            break;
          }
          case 48: {
            ToMapId = input.ReadInt32();
            break;
          }
          case 56: {
            ToRoomId = input.ReadInt32();
            break;
          }
          case 64: {
            Point = input.ReadInt32();
            break;
          }
          case 72: {
            Dist = input.ReadInt32();
            break;
          }
          case 80: {
            Force = input.ReadBool();
            break;
          }
          case 90:
          case 88: {
            params_.AddEntriesFrom(input, _repeated_params_codec);
            break;
          }
          case 96: {
            ToRoleId = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Step = input.ReadInt32();
            break;
          }
          case 16: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 24: {
            RoleId = input.ReadInt64();
            break;
          }
          case 32: {
            FromMapId = input.ReadInt32();
            break;
          }
          case 40: {
            FromRoomId = input.ReadInt32();
            break;
          }
          case 48: {
            ToMapId = input.ReadInt32();
            break;
          }
          case 56: {
            ToRoomId = input.ReadInt32();
            break;
          }
          case 64: {
            Point = input.ReadInt32();
            break;
          }
          case 72: {
            Dist = input.ReadInt32();
            break;
          }
          case 80: {
            Force = input.ReadBool();
            break;
          }
          case 90:
          case 88: {
            params_.AddEntriesFrom(ref input, _repeated_params_codec);
            break;
          }
          case 96: {
            ToRoleId = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SS_game_object_jump_msg : pb::IMessage<SS_game_object_jump_msg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS_game_object_jump_msg> _parser = new pb::MessageParser<SS_game_object_jump_msg>(() => new SS_game_object_jump_msg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS_game_object_jump_msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Game.Qe.Common.Msg.Proto.GameMsgReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS_game_object_jump_msg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS_game_object_jump_msg(SS_game_object_jump_msg other) : this() {
      type_ = other.type_;
      id_ = other.id_;
      fromMapId_ = other.fromMapId_;
      fromRoomId_ = other.fromRoomId_;
      toMapId_ = other.toMapId_;
      toRoomId_ = other.toRoomId_;
      point_ = other.point_;
      params_ = other.params_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS_game_object_jump_msg Clone() {
      return new SS_game_object_jump_msg(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private int type_;
    /// <summary>
    ///对象类型 1 : NPC 2 : drop -- 掉落  5 : growable -- 植物 7 : effect -- 特效对象 10 : gang -- 门派石 14：mechanism -- 机关
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private long id_;
    /// <summary>
    ///对象表ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "fromMapId" field.</summary>
    public const int FromMapIdFieldNumber = 3;
    private int fromMapId_;
    /// <summary>
    ///来源地图ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FromMapId {
      get { return fromMapId_; }
      set {
        fromMapId_ = value;
      }
    }

    /// <summary>Field number for the "fromRoomId" field.</summary>
    public const int FromRoomIdFieldNumber = 4;
    private int fromRoomId_;
    /// <summary>
    ///来源房间ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FromRoomId {
      get { return fromRoomId_; }
      set {
        fromRoomId_ = value;
      }
    }

    /// <summary>Field number for the "toMapId" field.</summary>
    public const int ToMapIdFieldNumber = 5;
    private int toMapId_;
    /// <summary>
    ///目标地图ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ToMapId {
      get { return toMapId_; }
      set {
        toMapId_ = value;
      }
    }

    /// <summary>Field number for the "toRoomId" field.</summary>
    public const int ToRoomIdFieldNumber = 6;
    private int toRoomId_;
    /// <summary>
    ///目标房间ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ToRoomId {
      get { return toRoomId_; }
      set {
        toRoomId_ = value;
      }
    }

    /// <summary>Field number for the "point" field.</summary>
    public const int PointFieldNumber = 7;
    private int point_;
    /// <summary>
    ///坐标
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Point {
      get { return point_; }
      set {
        point_ = value;
      }
    }

    /// <summary>Field number for the "params" field.</summary>
    public const int ParamsFieldNumber = 8;
    private static readonly pb::FieldCodec<int> _repeated_params_codec
        = pb::FieldCodec.ForInt32(66);
    private readonly pbc::RepeatedField<int> params_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///对象参数 NPC：血量 掉落：时间 植物：时间 机关：血量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Params {
      get { return params_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS_game_object_jump_msg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS_game_object_jump_msg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Id != other.Id) return false;
      if (FromMapId != other.FromMapId) return false;
      if (FromRoomId != other.FromRoomId) return false;
      if (ToMapId != other.ToMapId) return false;
      if (ToRoomId != other.ToRoomId) return false;
      if (Point != other.Point) return false;
      if(!params_.Equals(other.params_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (FromMapId != 0) hash ^= FromMapId.GetHashCode();
      if (FromRoomId != 0) hash ^= FromRoomId.GetHashCode();
      if (ToMapId != 0) hash ^= ToMapId.GetHashCode();
      if (ToRoomId != 0) hash ^= ToRoomId.GetHashCode();
      if (Point != 0) hash ^= Point.GetHashCode();
      hash ^= params_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Type);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Id);
      }
      if (FromMapId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FromMapId);
      }
      if (FromRoomId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(FromRoomId);
      }
      if (ToMapId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ToMapId);
      }
      if (ToRoomId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ToRoomId);
      }
      if (Point != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Point);
      }
      params_.WriteTo(output, _repeated_params_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Type);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Id);
      }
      if (FromMapId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FromMapId);
      }
      if (FromRoomId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(FromRoomId);
      }
      if (ToMapId != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ToMapId);
      }
      if (ToRoomId != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(ToRoomId);
      }
      if (Point != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Point);
      }
      params_.WriteTo(ref output, _repeated_params_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (FromMapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FromMapId);
      }
      if (FromRoomId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FromRoomId);
      }
      if (ToMapId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ToMapId);
      }
      if (ToRoomId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ToRoomId);
      }
      if (Point != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Point);
      }
      size += params_.CalculateSize(_repeated_params_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS_game_object_jump_msg other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.FromMapId != 0) {
        FromMapId = other.FromMapId;
      }
      if (other.FromRoomId != 0) {
        FromRoomId = other.FromRoomId;
      }
      if (other.ToMapId != 0) {
        ToMapId = other.ToMapId;
      }
      if (other.ToRoomId != 0) {
        ToRoomId = other.ToRoomId;
      }
      if (other.Point != 0) {
        Point = other.Point;
      }
      params_.Add(other.params_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = input.ReadInt32();
            break;
          }
          case 16: {
            Id = input.ReadInt64();
            break;
          }
          case 24: {
            FromMapId = input.ReadInt32();
            break;
          }
          case 32: {
            FromRoomId = input.ReadInt32();
            break;
          }
          case 40: {
            ToMapId = input.ReadInt32();
            break;
          }
          case 48: {
            ToRoomId = input.ReadInt32();
            break;
          }
          case 56: {
            Point = input.ReadInt32();
            break;
          }
          case 66:
          case 64: {
            params_.AddEntriesFrom(input, _repeated_params_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = input.ReadInt32();
            break;
          }
          case 16: {
            Id = input.ReadInt64();
            break;
          }
          case 24: {
            FromMapId = input.ReadInt32();
            break;
          }
          case 32: {
            FromRoomId = input.ReadInt32();
            break;
          }
          case 40: {
            ToMapId = input.ReadInt32();
            break;
          }
          case 48: {
            ToRoomId = input.ReadInt32();
            break;
          }
          case 56: {
            Point = input.ReadInt32();
            break;
          }
          case 66:
          case 64: {
            params_.AddEntriesFrom(ref input, _repeated_params_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
